name: Tag and Release

on:
  push:
    branches: [master]
defaults:
  run:
    shell: bash    
jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: paulhatch/semantic-version@v4.0.2
        id: semantic-version
        with:
          tag_prefix: "v"
          major_pattern: "MAJOR"
          minor_pattern: "MINOR"
          format: "${major}.${minor}.${patch}"
          short_tags: false
          bump_each_commit: true
      - name: Create Tag
        env:
          TAG: v${{ steps.semantic-version.outputs.version }}
        continue-on-error: true
        run: |
          git tag
          git tag $TAG
          git push --tags
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.1"
      - name: Build Go binary
        run: |
          go build
      - name: Release Go binary
        env:
          TAG: v${{ steps.semantic-version.outputs.version }}
          TARGET_REPO: arrikto/vault-kv-get
          GITHUB_TOKEN: ${{ secrets.RELEASES_GITHUB_TOKEN }}
        run: |
          gh release create $TAG vault-kv-get -R $TARGET_REPO -t "Release $TAG"
